### PR TITLE
Add clinical trials figure

### PR DESCRIPTION
**Pull request by agitter**
### Description of the proposed additions or changes

Adds the clinical trials figure and expands the scheduled workflow that re-generates the figure

### Related issues

#406 #465

### Checklist

- [x] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by agitter** [comment]
I ran into the pandoc-fignos numbering bug described in https://github.com/tomduck/pandoc-fignos/issues/76 Fortunately, the workaround in https://github.com/tomduck/pandoc-fignos/issues/76#issuecomment-613190630 worked.

We'll have to add `secno=1` after all figure ids until the bug is fixed.

**Comment by agitter** [comment]
I added a basic description of the figure, so this is now ready for review.  There are more ideas for clinical trials data in #406.  However, I'd like to work on merging this before implementing any of those so that the updated nightly clinical trials data update added here starts to run.

**Comment by agitter** [comment]
I updated the nightly workflow to support versioned figures.  This pull request is now linked to #512.  They should be merged on the same day.

There may be errors because I can't fully test to new external resources scripts until they run in the nightly GitHub Actions workflow.  After we merge, I'll watch the CI logs to see whether this worked.

**Comment by rando2** [comment]
#512 just merged so will merge this ASAP

**Comment by rando2** [comment]
Manubot approved and I want this to merge as close to #512 as possible, so going ahead!

**Comment by agitter** [comment]
Thanks @rando2.  I made a note to check what happens with the nightly external resources update tonight so I can fix any errors that arise.

**Pull request merged**
