### PR TITLE
Regenerate pathogenesis docx with correct author list

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

#849 describes the issue -- two authors were left off the pathogenesis ms at submission. We'd like to fix the arXiv submission ASAP and then fix the journal submission as part of the review process.

### Related issues

#849

### Suggested reviewers (optional)

@cgreene but I'm not even sure this PR needs to be approved or merged, it just needs to build so that I can pull the docx from the artifact.

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by agitter** [comment]
What do you think about adding an additional header sentence to the first page (#839) before resubmitting to arXiv?  I'm going to push an example to my pharmaceuticals pull request tonight.  If that text looks good, we can add it here as well.

**Comment by rando2** [comment]
That sounds perfect @agitter!

**Comment by cgreene** [comment]
I approve conceptually but will wait for @agitter's header :)

**Comment by rando2** [comment]
OK, I generated a new pdf from the docx and requested to replace the existing version with the new one!

We have received your replacement of 2102.01521. Your temporary 
submission identifier is: submit/3602789.

I think this issue can be closed.

**Comment by agitter** [comment]
@rando2 do you want to merge this to tag v2 of the pathogenesis manuscript once it is added to the output branch??

**Comment by rando2** [comment]
@agitter that's a great idea! If it looks okay and someone could approve, I can move ahead with doing that!

**Review by agitter — COMMENTED** [review]
I checked the docx artifact.  Looks good to me.

**Review by agitter — APPROVED** [review]

**Pull request merged**
