### PR TITLE
Add LaTeX export for ACM-BCB

### PR DESCRIPTION
**Pull request by agitter**
This adds preliminary LaTeX export for the ACM-BCB submission.  The big picture is that we can automatically generate a base document for the submission, but it will require a fair amount of manual editing before it will build with the ACM sigconf proceedings template.  Because of our tight timeline, we'll need to decide how much more to automate versus prioritizing manuscript content.

There is now a list `individual-docx-manuscripts.txt` of manuscripts to export as docx and another list `individual-latex-manuscripts.txt` to export for LaTex.  Exporting for LaTeX generates a .tex and a .bib file that contains reference metadata from Manubot.  Hopefully those two outputs are work together.  I haven't tried building a PDF yet.

This builds on two experimental rootstock pull requests: https://github.com/manubot/rootstock/pull/384 and https://github.com/manubot/rootstock/pull/386  One of those upgrades the version of Pandoc.  That will cause some changes to our HTML and PDF outputs, so we'll need to check those carefully before merging.  I also had to further update the environment to resolve new package incompatibilities.  However, the newer version of Pandoc is needed to extract the .bib file.

When outputting .tex files, Pandox uses a LaTeX template.  This is different from what ACM refers to as a template, which is an example .tex file.  The Pandoc version of a template can access metadata variables, like our Markdown template for the front matter.  This strategy isn't compatible with how Manubot writes author information and some other metadata.  I can resolve some of these incompatibilties, but we'll need to decide what missing metadata (authors? affiliations?) is high priority.

I didn't test images.  Those will probably not work immediately.

`@misc` URL citations currently don't include the URL in the bib file.

Here are the current outputs (.txt added so GitHub will allow the attachment):
- [methods-manuscript.tex.txt](https://github.com/greenelab/covid19-review/files/6388056/methods-manuscript.tex.txt)
- [methods.bib.txt](https://github.com/greenelab/covid19-review/files/6388057/methods.bib.txt)

### CODE REVIEW

**Comment by rando2** [comment]
Thank you so much for working on this @agitter! I think as long as we are getting the markdown document into something that is vaguely compatible with the template, it will be a lot easier to clean up the template. I'm not sure how well I can review this PR because it is really complex. @mprobson has also said he can take a look, but I imagine he'll have the same issue with not quite understanding the under-the-hood of Manubot well enough. I can definitely help with reviewing the outputs, though.

**Comment by agitter** [comment]
I'm happy to walk through some of the build script changes if you comment on anything you're curious about.  The `build.sh` script is a little messy because I copied a large code block while trying to debug the tex export.

The main issue is that the newer version of Pandoc does make the HTML and PDF outputs look different.  A short term workaround would be to create two conda environments and manually toggle between them when we're preparing LaTeX export versus making general builds the rest of the time.  It would be better to fix the formatting issues, but we have so little time.

For review, you can ignore all the `build/assets/acmart-master` files.  Those are just the files I downloaded from ACM.  The main focus of the review (where @mprobson may be able to help) is the two attachments in my original post.  We should identify any major problems in the exported .tex file that I can try to fix (e.g. authors) so we can move on to the content.

**Comment by mprobson** [comment]
@agitter this is an amazing effort! I looked through the committed files and I think I understand most of what they're doing. I'll try to chime in with what I can parse but apologies if I missed something. 

---

As far as I can tell the generated .bib file looks correct.

---

We should be able to generate a rough pdf in the file stage of the `build.sh` file using one of two methods, depending on what's available in the CI environment:

`latexmk -pdf output/$INDIVIDUAL_KEYWORD-manuscript.tex && latexmk -pdf -c output/$INDIVIDUAL_KEYWORD-manuscript.tex`

or

```
pdflatex output/$INDIVIDUAL_KEYWORD-manuscript.tex &> /dev/null
bibtex output/$INDIVIDUAL_KEYWORD &> /dev/null  # not sure about this line if we're using natbib
pdflatex output/$INDIVIDUAL_KEYWORD-manuscript.tex &> /dev/null
pdflatex output/$INDIVIDUAL_KEYWORD-manuscript.tex &> /dev/null
```

I use the first command locally to build my finished pdfs (and clean the outputs, everything after the && is just housekeeping) and the seconds set of commands is from this [blog post][1], which links to bibtex's [instructions][2]. We may even be able to use [pandoc][3], e.g. `pandoc methods.md -o methods.pdf` and potentially skip the .tex and .bib file generation step.

---

Also, I don't know that all the `build/assets/acmart-master/*` files are necessary. The `acmart` style should be available by default depending on the environment and LaTeX installation. If not, we can probably install it via whatever LaTeX distribution we have. I think we'd only want to include the .cls file (and not everything else) if none of that works.

---

The majority of my observations are about the generated .tex file.

1. We should have a method to manually specify the style as `docmentclass: acmart` and `classoptions: sigconf` (see below).

2. In the .tex file I expected the bibliography to look something like:

```
\bibliographystyle{ACM-Reference-Format}
\bibliography{methods.bib}
``` 

The linked Pandoc-to-LaTeX template does have functionality to generate this but I don't see it being employed even though I see the `natbib` option in `latex.yaml`.

3. In general, it looks like Pandoc expects a yaml stub at the top of the file to fill in all the variables. It appears we can generate and provide this separately via the `metadata-files` [option][3], e.g. the list of authors and per paper specific LaTeX/YAML configurations, including the document class and bibliography style options mentioned above.

4. I think we should consider maintaining (or forking) our own template file. You linked several good examples and I'll add one more here: [acm-pandoc-conf.tex](https://gist.githubusercontent.com/wgroeneveld/b6e2751c6da2a7bac73f668ddff5c3d0/raw/a7a0dd3b42b261a8b19a93dd39646682d6559af5/acm-pandoc-conf.tex) from this (very helpful) [blog post][4]. I can try and create a minimal working example if that would be helpful although I am still trying to figure out how to test the Manubot pipeline. 

[1]: https://opensource.com/article/18/9/pandoc-research-paper
[2]: http://www.bibtex.org/Using/
[3]: https://pandoc.org/MANUAL.html
[4]: https://brainbaking.com/post/2021/02/writing-academic-papers-in-markdown/

**Comment by agitter** [comment]
Thanks for reviewing.  You have a good understanding of what's going on.

> We should be able to generate a rough pdf in the file stage of the build.sh file

This should be possible, but I anticipate we'll run into a lot of minor details when trying to fully automate pdf generation that will slow us down.  https://github.com/manubot/rootstock/issues/249 and https://github.com/manubot/rootstock/pull/256 have additional context about building the pdf in the continuous integration environment with pandoc (the old Travis CI one, which was less flexible).

The workflow I had in mind was
- automatically generate .tex and .bib source files
- (optional) run a simple script to fix some .tex file issues via string replacement
- download and manually polish the .tex to fix issues noted above and others
- locally build a pdf

What do you think about that?

> I don't know that all the build/assets/acmart-master/* files are necessary

I can delete these and keep only the .cls file.  My goal was to provide what is needed for someone building locally.

> In general, it looks like Pandoc expects a yaml stub at the top of the file to fill in all the variables.

Yes, Manubot has a different convention for setting authors, but we can modify the metadata in the yaml stub or pass metadata to pandoc as a command line argument.  I'm passing the title via the command line for individual manuscripts to override the title in the yaml block.  Author metadata is probably worth automating before we merge.

> I am still trying to figure out how to test the Manubot pipeline.

To run this locally
- Create and activate the conda environment ([instructions](https://github.com/manubot/rootstock/tree/main/build#environment)) using the updated `environment.yml` from this branch
- From the root directory of the repository run `BUILD_HTML=false BUILD_PDF=false BUILD_INDIVIDUAL=true build/build.sh` (save time by not building the full manuscript, only the methods manuscript)

If I'm forgetting a step, I can help debug.  I agree that we would need to fork a template if we want to perfect the automated build.  If we instead can settle with a .tex file that has content that can by copied into the ACM template, we can live with a lot of errors in the template.

**Comment by rando2** [comment]
I looked through the Manubot artifact, and the only odd thing I noticed in the HTML and PDF builds is that, while Figure 1 usually doesn't work in the HTML build, it doesn't work in a different way here (prints the figure legend twice, whereas in prior builds it just didn't render).

The .tex file does build into a pdf, and the encodings of headings and such all seemed to work! The citations aren't there yet but I know that's a work in progress. It seems like this will make it WAY easier to get things formatted for ACM than it would have been with just the .md file! Here's the pdf in case anyone wants to see:
[methods-manuscript.pdf](https://github.com/greenelab/covid19-review/files/6394866/methods-manuscript.pdf)

**Comment by agitter** [comment]
> Figure 1 usually doesn't work in the HTML build, it doesn't work in a different way here

That's interesting.  If you check the HTML source, it now has the full figure caption as the alt text.  When the figure is missing (which happens because we're downloading just the .html file instead of the full output including the images directory), the alt text is displayed instead.

The whitespace on the PDF is different, but we may be able to tolerate that.

That's great the tex builds into a pdf.  Did you have to modify anything to get it to build? If you add these lines from @mprobson above do the references work?
```
\bibliographystyle{ACM-Reference-Format}
\bibliography{methods.bib}
```

I'm going to experiment with adding author metadata.

**Comment by mprobson** [comment]
> What do you think about that?

That makes a lot of sense, especially given the time pressure we're under.

> I can delete these and keep only the .cls file. My goal was to provide what is needed for someone building locally.

That sounds good. I _think_ we can get away without including the .cls file as well since most TeX distributions should include it but it definitely doesn't hurt to have a copy around for local deployment just in case.

> Author metadata is probably worth automating before we merge.

Agreed. It seems like you're currently working on a solution to this but please let me know if there's something on my end I can do to test, debug, code, etc.

> If I'm forgetting a step, I can help debug.

This worked perfectly after I installed `conda` via `homebrew install --cask anaconda` and set it up via  `conda init`.
(I'm mostly putting this here for my own future reference but I did have to move the conda initalization code from `.bash_profile` to `.profile` because of my particular setup).

I did have a small issues with Linux/BSD incompatibility. It turns out the `--lines` options is not support on the native MacOS version of `head`. Editing `build.sh` to use `head -n 1` instead solved the issue and should be compatible with Linux systems as well. I'm happy to submit a small PR to fix this once this is merged (as a GitHub novice, I'm not entirely sure how to do a PR on top of another PR).

>  I agree that we would need to fork a template if we want to perfect the automated build.

Also agreed, although I plan to try experimenting with this so the generated pdf utilizes the acmart document class and bibliography styles. I _think_ I can do this with the current template but I'll create my own if not. Do we have a preferred location if I do create one? I can just post a Gist for now if I do end up making one.

**Comment by agitter** [comment]
@mprobson that ACM template you found helps a lot.  I switched to that, and it gets us much closer to the end product we want.  I also confirmed that it is possible to provide pandoc an additional metadata file and override/supplement the metadata in the YAML block in the markdown file.  That makes life easier for us.  See `example-methods-metadata.yaml` for a temporary demonstration.

> I did have a small issues with Linux/BSD incompatibility.

I'll make another commit to change this.  It works locally for me on Windows with `-n`.

@mprobson would you like to take the lead on forking the ACM template and customizing it for our needs?  It can be a gist for now.  Once it is stable, you could make a pull request to add it here.

I can focus on writing a metadata file with the author information needed for the template.  Getting author names and email (if we want those) is straightforward.  Affiliations are more complicated.  Manubot supports a list of free text affiliations, and the current ACM template expects a single institution, department, city, and country per author.  The easiest fix would be to roll everything into a single `affiliation` string in the tex template.

Here's the tex file using the new template and additional metadata:
[methods-manuscript.tex.txt](https://github.com/greenelab/covid19-review/files/6395149/methods-manuscript.tex.txt)

**Comment by rando2** [comment]
@agitter I'm not sure if you need it, but I opened #949 to update the author list for this manuscript, just in case that's helpful.

**Comment by mprobson** [comment]
@agitter, I just regenerated the paper from your latest commits on this branch and it's looking good! There are a few errors to fix but I will work on those via template/variables (see below).

The `example-methods-metadata.yaml` file looks great. I assume we can programmatically generate the entire author list and append it there along with any other values we need.

> Is that compatible with the ACM style?

ACM LaTeX template expects something like the following:

```
\author{Charles Palmer}
\orcid{1234-5678-9012} % optional
\affiliation{%
  \institution{Palmer Research Laboratories}
  \city{San Antonio}
  \state{Texas} % optional
  \country{USA}}
\email{cpalmer@prl.com} % maybe optional
```

There are some other optional fields (post code, street address, etc). You can read more about the acmart package at the [CTAN](https://www.ctan.org/pkg/acmart) repo. The documentation [PDF](https://mirrors.concertpass.com/tex-archive/macros/latex/contrib/acmart/acmart.pdf) is what I've found most useful.

I just saw @rando2's latest PR. It seems like since we have control over the affiliation format we can standardize it by hand for the ~10 authors on this manuscript so it's something like: Dept., Institution, City, Country, which should be easily parsable and translatable. As a note, multiple affiliations are allowed in this format, so we would just repeat it for each author. I'm not totally sure how to do this on the template side, we may need to make this a loop. I can look at Pandoc's docs to confirm.

I'm happy to take the lead on crafting the template file. I plan to hard code some of the following but it might be something we put in the per-paper yaml file above in future iterations.

- Removing anonymous (currently prevents building without being the metadata variable being set to false or true)
- Bibliography and style
- Add missing longtables package
- Remove extraneous packages

I think the last big hurdle (aside from generating the author list, which you're already working on) is ensuring figures (and citations?) are generated correctly.

**Comment by mprobson** [comment]
I've started a fork here: https://gist.github.com/mprobson/f339cfdf0f1d0de6ff6b258a852e4bb4 and removed the anonymous option. I still need to complete the aforementioned todos (bib, longtables, etc). I'm also realizing that a gist may not be the best place for collaboration but we'll figure it out.

**Comment by agitter** [comment]
> I assume we can programmatically generate the entire author list and append it there along with any other values we need.

Yes, my plan is to write a small Python script that reads in the `metadata.yaml` file with Manubot-style metadata and writes a simpler yaml file for than pandoc tex export.  We'll have full flexibility to map any metadata we current have for authors to any metadata we want to use in your template.

For the author information, I'm following this part of the pandoc manual:
> Variables can contain arbitrary YAML structures, but the template must match this structure. The author variable in the default templates expects a simple list or string, but can be changed to support more complicated structures. The following combination, for example, would add an affiliation to the author if one is given:
```
---
title: The document title
author:
- name: Author One
  affiliation: University of Somewhere
- name: Author Two
  affiliation: University of Nowhere
...
```

If it allows arbitrary yaml, we could make affiliation into a list with the more precise fields supported by the ACM LaTeX template
```
---
title: The document title
author:
- name: Author One
  affiliations:
  - institution: Palmer Research Laboratories
    city: San Antonio
    state: Texas
    country: USA
  - institution: My Other Institution
    city: A Very Nice City
    country: Atlantis
...
```

Rather than try to parse the free text affiliations we're using for Manubot, we could duplicate them and specify them in new fields in `metadata.yaml`.  It would create some manual effort but be reliable.  Maybe we nest it under `manuscripts`:
```
    manuscripts:
      methods:
        order: 1
        contributions:
          - Project Administration
        affiliations:
        - institution: Palmer Research Laboratories
          city: San Antonio
          state: Texas
          country: USA
        - institution: My Other Institution
          country: Atlantis
```

Then I could grab the author name and the affiliations list from there along with other optional fields like email.  If this sounds okay, we should next confirm that the yaml metadata block can support a list of affiliations and that works as expected in the template.

**Comment by mprobson** [comment]
>  If this sounds okay, we should next confirm that the yaml metadata block can support a list of affiliations and that works as expected in the template.

I just confirmed that I can modify the template to match the middle example with multiple affiliations. Basically, I loop over the affiliation list and print each piece one by one inside the loop. I think wherever you want to store the hand curated affiliation information is fine by me. Just let me know the yaml format of the parsed version and I'll update the template accordingly.

**Comment by agitter** [comment]
This format from above should work for me:
```
---
title: The document title
author:
- name: Author One
  affiliations:
  - institution: Palmer Research Laboratories
    city: San Antonio
    state: Texas
    country: USA
  - institution: My Other Institution
    city: A Very Nice City
    country: Atlantis
...
```
Are there any modifications or additional fields you would like to have?  I can match whatever you'd like.

That's good news that multiple affiliations work.

**Comment by mprobson** [comment]
I think the final format in the yaml file should be the following:

```
---
author:
- name: Author One
  email: ao@p.rl
  orcid: 0000-1234-5678-9012
  affiliations:
  - institution: Palmer Research Laboratories
    city: San Antonio
    state: Texas
    country: USA
  - institution: My Other Institution
    city: A Very Nice City
    country: Atlantis
...
```

ORCID and State are both optional and will be inserted if they exist but their absence won't break anything. I don't think order matters so as long as we have those fields (name, email, affiliation(s): institution, city, country), for each author the template should work. The acmart style also supports multiple emails but I am not going to support this case (for now) because we only allow a single email in the default metadata.yaml file in content.

I'll push the updated template that handles multiple affiliations in a few minutes.

**Comment by agitter** [comment]
We have a connection between the build script and new template!  I made a Python script to extract the metadata we need from the Manubot-style file and dump it to a new YAML file for Pandoc.  That works with @mprobson's template:
[methods-manuscript.tex.txt](https://github.com/greenelab/covid19-review/files/6402938/methods-manuscript.tex.txt)

Can you please make email optional as well?  The consortium author, if we include it, will not have email.  Should we also make affiliations optional because of the consortium?  Currently, I insert a default value.

Should the `\institution{$author.affiliations.department$}` line use `\department`?

I tried setting the `bibliography` variable to the string `methods.bib`, but it isn't showing up in the tex output.  I think this variable is processed by Pandoc and isn't passed through like other metadata.  We could try using a different variable `bibfile`.  The metadata file I pass to Pandoc is:
[pandoc-metadata.yaml.txt](https://github.com/greenelab/covid19-review/files/6402951/pandoc-metadata.yaml.txt)

A next step would be to add the duplicate affiliation data in this more structured format.  I added @rando2's as an example.

**Comment by mprobson** [comment]
> Can you please make email optional as well?

Good catch, fixed now. I thought the acmart styl file did not allow this but we can clean up by hand.

> Should the \institution{$author.affiliations.department$} line use \department?

Yes, that's a copy/paste error. It's fixed now. I realized that we likely aren't using it but I'm leaving it in since it won't hurt. I also added the (optional) state line as well.

> We could try using a different variable `bibfile`.

I will test this locally to confirm and update the template accordingly.

> figure support

I spoke with @rando2 and she seems to think figures are breaking even in the HTML version.

I think we should automate the following:
- adding URLs for website references or converting these citations to URLs in text
- fixing section number with Pandoc settings

I think we'll need to do the following by hand for now:
- compacting affiliations, which take the entire first page
- removing the duplicate references section header
- removing Manubot front matter (author list)
- fixing the competing interests and contributions tables or removing the contributions, which are probably not typical in ACM

You are right that CoI and contributions are atypical and should be removed.

These are just my opinions based on what's reasonable but you have a better insight on the pandoc end.

> Should that be a new variable in the template?

I don't think I understand the question but extra variables won't hurt anything (I think).

**Comment by rando2** [comment]
>I spoke with @rando2 and she seems to think figures are breaking even in the HTML version.

It looks like Manubot might be building for #947 so we'll see what happens, but I haven't seen anything so far to make me think I have the figures working *correctly*

**Comment by agitter** [comment]
I made some progress on automating removing notes from the bib file and the duplicate author list.  I added abbreviations for the affiliations and deleted repeated text to save a little space.  The PDF is looking okay now.
[methods-manuscript.pdf](https://github.com/greenelab/covid19-review/files/6406599/methods-manuscript.pdf)
[methods.bib.txt](https://github.com/greenelab/covid19-review/files/6406600/methods.bib.txt)
[methods-manuscript.tex.txt](https://github.com/greenelab/covid19-review/files/6406602/methods-manuscript.tex.txt)

The only manual edit is to replace
```
References

\hypertarget{refs}{}
\begin{CSLReferences}{0}{0}
\end{CSLReferences}
```
in the tex file with
```
\bibliography{methods.bib}
```

I can easily drop the conflicts of interest and contributions, but leaving the conflicts (at least for me and Lucy) does seem like a good idea.

> adding URLs for website references or converting these citations to URLs in text

How would we automate this?  They are lost in the json to bib conversion that Pandoc does.  I'll think about it more, but don't have any easy ideas.

> Should that be a new variable in the template?

Ignore this prior idea.  I think we should just make the manual edit that I made above.

This is the most I know how to automate unless someone has more suggestions.  I'm happy to keep making revisions to minimize the manual labor needed for the submission.

**Comment by mprobson** [comment]
The authors and affiliations look much better now! We can also use the `\additionalaffiliation{}` command to move some of the extra affiliations to footnotes if we really need it.


In that case, maybe remove contributions (from the paper - I think it's important to keep online) and move CoI to a footnote? The best guidance I could find from ACM is here: https://www.acm.org/publications/policies/conflict-of-interest

> a footnote could be placed on the first page noting the nature of the COI (e.g., "The second author has received research funding from Corporation X which makes Product Y, described in the text.")

> How would we automate this?

That's a good question. I had assumed there was a LaTeX package to auto-detect and format URLs, I wasn't thinking about the Pandoc json to bib conversion. May be future work... It's definitely not something to stress for the submission but maybe the camera ready.

I'll keep looking for other things to improve in addition to the text!

**Comment by agitter** [comment]
> In that case, maybe remove contributions (from the paper - I think it's important to keep online) and move CoI to a footnote?

Should I use another metadata variable for this?  I could construct a string like "Author A has conflict X.  Author B has conflict Y."  Then we could add something like
```
$if(conflicts)$
	\footnote{$conflicts$}
$endif$
```
after the body.  Then I could remove the Markdown source file with the conflicts and contributions table.

> It's definitely not something to stress for the submission but maybe the camera ready.

Agreed.  We can come up with something given more time, but this may no longer be a critical issue.

**Comment by agitter** [comment]
To illustrate the website references, here are CSL JSON entries for websites
```
  {
    "URL": "https://www.physicianscientists.org/page/summer-research-pilot-program",
    "title": "Undergraduate Mentoring - American Physician Scientists Association",
    "type": "webpage",
    "id": "DGTDsJZy",
    "note": "This CSL JSON Item was automatically generated by Manubot v0.4.1 using citation-by-identifier.\nstandard_id: url:https://www.physicianscientists.org/page/summer-research-pilot-program\nLoaded from an external bibliography file by Manubot.\nsource_bibliography: manual-references-2021-02-08.json\noriginal_id: DGTDsJZy"
  },
  {
    "id": "snhvVGmP",
    "type": "webpage",
    "title": "Zotero | Your personal research assistant",
    "abstract": "Zotero is a free, easy-to-use tool to help you collect, organize, cite, and share research.",
    "URL": "https://www.zotero.org/",
    "accessed": {
      "date-parts": [
        [
          "2021",
          4,
          30
        ]
      ]
    },
    "note": "This CSL Item was generated by Manubot v0.5.1 from its persistent identifier (standard_id).\nstandard_id: url:https://www.zotero.org"
  }
```

after converting to bib with Pandoc and stripping the `note` field with a regex we get
```
@misc{DGTDsJZy,
  title = {Undergraduate {Mentoring} - {American} {Physician}
    {Scientists} {Association}}
}
@misc{snhvVGmP,
  title = {Zotero \textbar{} {Your} Personal Research Assistant}
}
```

**Comment by mprobson** [comment]
> Should I use another metadata variable for this?

Yes, that'd be perfect. I've already pushed an update to the template to insert an unnumbered footnote on the first page containing the conflict string. This matches the formatting used in the [sample-sigconf.pdf](https://github.com/greenelab/covid19-review/files/6407293/sample-sigconf.pdf) distributed by ACM (and attached here for reference).

The website translation is very helpful but I'm not sure what do about it at the moment. Maybe we can tinker with Pandoc? That's a long shot though.

**Comment by agitter** [comment]
> Edit: I realized every time I change the gist you need to update the metadata link to it. 

That's not a problem for me.  I'm editing these files regularly anyway.  We can integrate it into this repo after we merge this pull request.

I'll work on the conflicts statement after pushing some text edits to #947.

**Review by mprobson — APPROVED** [review]
This all looks good (pending conflicts integration). I'm not in a place to comment on build/update-latex-metadata.py but it seems to work.

Minor / Unimportant notes (please feel free to ignore - not blocking merge):
- Can remove acmart.bib and sample-sigconf.tex (unused)
- Can add (back) Makefile, bbx, cbx, dbx (but I'm not sure if we need?)

**Comment by mprobson** [comment]
Just pushed a change to the gist enabling `bibfile` which automatically adds the right bibliography line. Now we just need to automate removing the CSLreference section.

**Comment by rando2** [comment]
@mprobson I usually manually change the acknowledgements, do you want me to send you the correct ones for this paper?

**Comment by agitter** [comment]
> I can hardcode but the template could ingest the following

I'll updated to add that block into the YAML I generate.

> Minor / Unimportant notes

I can fix those.

**Comment by mprobson** [comment]
> I usually manually change the acknowledgements...

That's great, thanks! I think the bigger issue is that we need to use \section*{Acknowledgments} and I'm not sure how to automate that.

**Comment by agitter** [comment]
I pushed changes that resolve most/all of the issues above:
- clean up the included ACM files
- only show the CCS concepts section when exporting as tex
- add the ACM metadata and conflicts statement for the template
- suppress the references section in the markdown
- exclude `70.coi-contribs.md` (conflicts table, contribution table, acknowledgements)
- add a new markdown file for methods acknowledgements and make the section unnumbered

The acknowledgments section now shows up as
```
\hypertarget{acknowledgements}{%
\section*{Acknowledgements}\label{acknowledgements}}
\addcontentsline{toc}{section}{Acknowledgements}
```
@rando2 you can edit the content in `61.methods-ack.md` if you need to edit the acknowledgements text for this individual manuscript.

I'm happy with this tex output.  It's a lot cleaner than I would have guessed.  From here, should we create a new issue with a single checklist of manual changes needed before submitting?

Latest version:
[methods-manuscript.pdf](https://github.com/greenelab/covid19-review/files/6408323/methods-manuscript.pdf)
[methods-manuscript.tex.txt](https://github.com/greenelab/covid19-review/files/6408324/methods-manuscript.tex.txt)

**Comment by agitter** [comment]
I just realized we don't have a funding statement anywhere.  Should we add that to `61.methods-ack.md`?  I think that would be best in terms of making it quickly and saving space.

**Comment by mprobson** [comment]
Wow, that's amazing! I agree re: funding statement. I usually put my sources in the acknowledgements.

I'm currently getting a weird error trying to build the latest commits:

```
raceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'commit'
```

I suspect that something has gone wrong with my python but wanted to confirm it's working for you.

**Comment by agitter** [comment]
> I suspect that something has gone wrong with my python but wanted to confirm it's working for you.

Strange.  It is working for me.  Is that error coming from Manubot or my script?

**Comment by mprobson** [comment]
It's definitely a system configuration issue on my end, although I am not sure what changed... I have some weird combination of Tmux, Conda, and MacOS... I re-ran on a known good commit and it still fails. conda deactivate/activate doesn't fix it nor does destroying and recreating the environment. I imagine it's just something I need to debug on my own.

Here's the command plus error:
```
(manubot) C02YD02QJGH8:covid19-review mrobso01$ BUILD_HTML=false BUILD_PDF=false BUILD_INDIVIDUAL=true build/build.sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'commit'
```

**Comment by mprobson** [comment]
I think I figured out what's happening... I seem to be dying on this line:

```
EXTERNAL_RESOURCES_COMMIT=$(curl -sS https://api.github.com/repos/greenelab/covid19-review/branches/external-resources | python -c "import sys, json; print(json.load(sys.stdin)['commit']['sha'])")

```

@rando2 and I share an IP address currently and she's getting rate limited by the GitHub API so I suspect I am now being throttled too...

**Pull request merged**
