### PR TITLE
add novavax to csv

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

Should fix the error noted in #1102

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Review by agitter — CHANGES_REQUESTED** [review]
The latest [failed build](https://github.com/greenelab/covid19-review/runs/5636637316?check_suite_focus=true) included these and additional platforms:
```
Missing platform information for SpikoGen, Turkovac, FAKHRAVAC, Razi Cov Pars, Soberana Plus, Novavax
```
Do you know the platform for the others?

**Comment by rando2** [comment]
> The latest [failed build](https://github.com/greenelab/covid19-review/runs/5636637316?check_suite_focus=true) included these and additional platforms:
> 
> ```
> Missing platform information for SpikoGen, Turkovac, FAKHRAVAC, Razi Cov Pars, Soberana Plus, Novavax
> ```
> 
> Do you know the platform for the others?

Oh, I'm sorry I didn't understand! I added them now. I'm going to take a look now and open a new PR, but I have an idea for how to make this automatic.

**Review by agitter — APPROVED** [review]

**Comment by agitter** [comment]
This fix addresses #1101, but I'll leave it open until we confirm the external resources build succeeds.

**Comment by rando2** [comment]
Thanks @agitter! Seems like there is a way to scrape this data but the way the HTML is organized really demands a generous interpretation of "semi" to be considered semi-structured. I think I almost have it, though, so I'll try to get a more permanent solution proposed tomorrow!

**Pull request merged**
