### PR TITLE
Add @gregszetoAI

### PR DESCRIPTION
**Pull request by cgreene**
### Description of the proposed additions or changes

In #631 @gregszetoAI provided a review + edits to the content. This pull requests aims to capture the contribution.

### Related issues

#631 

### Suggested reviewers (optional)

@gregszetoAI should definitely review. I attempted to gather the relevant fields from what I could find online. Also, please note that I indicated acceptance of the code of conduct and noted no conflicts of interest as of today. Please do not approve if these are not true.

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Review by rando2 — COMMENTED** [review]
Awesome!

**Review by rando2 — APPROVED** [review]

**Comment by cgreene** [comment]
We need to make sure that @gregszetoAI agrees and confirms the COI status/etc

**Comment by gregszetoAI** [comment]
Reviewed and confirmed info.

**Comment by cgreene** [comment]
Wonderful - thank you!

**Pull request merged**
