### PR TITLE
Add a discussion section with a vague outline

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

I am adding a new markdown file that can be used to start brainstorming for how we want to structure the discussion.

### Related issues

#460 

### Suggested reviewers (optional)

@tlukan will start outlining an analysis of how biases can affect the information we have. In terms of the addition of this section, anyone can review!

### Checklist

- [x] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by rando2** [comment]
We may want to include the summary figure from #488 in the discussion?

**Comment by rando2** [comment]
If someone doesn't mind approving, let's just create this section so we can work with it in #460. Happy to strike any text that we don't want merged in!

**Comment by yemarshall** [comment]
@rando2 @agitter @tlukan @soumitagh @dziakj1 
Somehow, I don't see Pull Requests or the corresponding files for what's currently in the latest manuscript draft under Discussion. How are reviewers/authors/contributors supposed to work on this or even notice when the discussion gets changed?
Also, this is a "vague outline" so it's meant to be rough, but I'm putting this comment as a reminder that what's currently under "equity" is too nonspecific/ambiguous to be useful. Here's what's currently there:
"Concerns about Equity in Healthcare
Scientific and medical research broadly is shaped by a number of biases, such as Eurocentrism, that
are of significant concern in the face of a global pandemic. Some concerns include: 1. Who is being
included in clinical trials? 2. While biotechnological developments are exciting, how likely are they to
be available to people broadly? 3. Even this review is likely biased (e.g., we look at traditional western
medicine in the nutraceuticals section and mainly report statistics from US and other data collection
services)
Risk of comorbid health conditions associated with more severe outcomes may be influenced by longterm damage caused by chronic stress related to traumatic social experiences [515], perhaps
mediated by cardiovascular risk factors [516], although the effects of chronic stress have not yet been
researched in the specic case of COVID-19 disparities."

My suggestions. If venturing into difficult topics and during global crises, it makes sense to be more specific and incorporate more emphasis on constructive directions.
For example,
A. "Concerns about equity in healthcare" change to --> "Considerations for equity in health"
-because considerations emphasizes constructiveness more than concerns, and "concerns" might be (mis)interpreted to mean that you don't think this will change (there are arguments for both how it might not change quickly in time and how it might change in time to save more lives -- since the point of the review is overall looking to support biotechnologies which are constructive it makes sense to also look for constructive directions here)
-because the 2 key aspects seen so far relate to possible differences in infection rates & possible differences in healthcare (& possible differences in factors related to both).
B. It doesn't work to use terms like "bias" and "eurocentric" without specifying what we mean. Also, we don't have deep enough sociology in this review to use terms like "eurocentric". Also, it can easily be shown to not make sense here because (i) SARS-CoV-2 is related to SARS-CoV-1 (focus area Asia) & MERS (focus area is in the name), (ii) infectious diseases research is about diseases which affect variety of areas and parts of population, (iii) some of our best related research is in influenza & one of our best related therapeutics is vaccines -- the antigens for influenza vaccines are chosen each year by considering both northern and southern hemispheres because of the seasons are out of phase, (iv) one of the main inequities we mention with specifics earlier in the text is within the US related to inequities that have long been discussed in context of several historical aspects as well as current society. Also the term "traditional western medicine" seems unclear? (v) there's nothing wrong with mentioning US statistics especially if one of the inequities identified is within the US. (vi) I'm not ignoring that it's easy to find patterns in various things in the world related to different countries and related to different segments of society and that there are both obvious and non-obvious explanations, but I am saying that these aspects are better addressed specifically and/or constructively and/or in depth (and possibly with the internal sensitivity/understanding that these are difficult topics and challenges even if everyone tries their best).
C. For the added sentence on the super-complex-sociological-health-etc. topic not seen in this PR but appearing somehow in the manuscript:
We shouldn't mention co-morbidities without mentioning also differences in infection rates -- this is a crucial point if you are looking for the most obvious directions-for-investigation and also if you are looking for ways to possibly reduce the deaths (and probably along with it the disproportionate patterns). Also, it doesn't make sense to just include one specific co-morbidity possible factor when there are so many others / don't need an example here because already mentioned many examples in the corresponding section. Also something just sounds not useful about mentioning this topic of research without explaining what the possible constructive directions are in terms of sociological or health improvements -- & during a pandemic it's even more important to focus on constructive directions so it's even more questionable to see this sentence by itself here.
D. There are efforts to make sure biotechnologies are made available, so it makes sense to mention it more positively.
E. With more input from public health contributors and other researchers/contributors, we could rewrite the same intentions but more specifically and more constructively (with more emphasis on positive directions). Maybe something like:
Considerations for equity in health
One of the strategies and goals of effective science and medical research is to avoid and remove biases. Also, identifying specific areas or aspects where health can be improved is a public health strategy which can both enhance program effectiveness directly in the area or aspect identified and indirectly in the whole population because infectious disease spreads and epidemics/pandemics are experienced by an interacting population. In the face of a global pandemic, some important considerations include the following: 1. What aspects of data are being collected? 2. Who is being included in clinical trials? 3. How do we make sure biotechnologies are widely available? 4. How do we improve consideration of health inequities in research and reviews, such as this one.

**Comment by rando2** [comment]
Hi @yemarshall, this PR is closed, but please feel free to open a new one with any suggestions! @tlukan is actively working on this section currently.

**Pull request merged**
