### PR TITLE
Add thumbnail

### LINKED ISSUE #669: Add manuscript thumbnail
Manubot allows specifying a thumbnail image that is used in the catalog and when the manuscript is shared on social media. Info at https://github.com/manubot/rootstock/blob/master/USAGE.md#thumbnail.

From https://manubot.org/catalog/:

image

I thought for example the SARS-CoV-2 virion in [Figure 2](https://greenelab.github.io/covid19-review/v/54de5be13deaeb2a650e017be717f1def7135da4/#fig:overview) would make a _fantastic_ thumbnail:

> image

If you'd like that to be your thumbnail (or anything else), just save the square image as thumbnail.png anywhere in the repo.

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

Per @dhimmel's suggestion, this PR adds a thumbnail image (thanks Daniel!)

### Related issues

closes #669

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Review by cgreene — APPROVED** [review]

**Comment by dhimmel** [comment]
I was thinking something more like:

> thumbnail_2

The thumbnail oftentimes will be small, so it's best to have something simple. The virion also would fit nicely in a square thumbnail.

If you have the vector source for Figure 2, @vincerubinetti might be able to help extract the perfect frame!

**Comment by agitter** [comment]
I believe https://github.com/greenelab/covid19-review/blob/master/content/images/N000-overview.pdf is the vector source for Figure 2.

**Comment by rando2** [comment]
Thanks @dhimmel and @agitter! Tagging @nilswellhausen in case he has any ideas or can make a thumbnail, otherwise I'll reach out to Vince!

**Comment by vincerubinetti** [comment]
> > thumbnail_2

This looks good to me, just white out the purple and blue bits that are being cut off (or zoom out a bit to fit them completely in the frame), then center the contents in the frame.

Also side note, I didn't see an obvious [link to the manubot manuscript](https://greenelab.github.io/covid19-review/) in the readme. That should probably be right at the top somewhere, emphasized, like:

[👁️ View the manuscript here 📜](https://greenelab.github.io/covid19-review/)

**Comment by vincerubinetti** [comment]
> I believe https://github.com/greenelab/covid19-review/blob/master/content/images/N000-overview.pdf is the vector source for Figure 2.

Zooming in on the viron portion, it looks like that was put in the pdf as a raster image. Who drew the viron originally? They'll need to provide the original inkscape or powerpoint slide they drew it in.

**Comment by rando2** [comment]
Thanks @vincerubinetti! @nilswellhausen is our resident scientific illustration expert and made the final image!

**Comment by nilswellhausen** [comment]
Screen Shot 2020-11-05 at 11 26 13 AM

**Comment by nilswellhausen** [comment]
In case you dont want to white out the rest.

**Comment by nilswellhausen** [comment]
What file format do you need the image for a thumbnail? I can do tiff, png, jpeg and pdf. For all other formats I might need help.

**Comment by rando2** [comment]
@nilswellhausen I believe png is perfect!! This looks AWESOME!

**Comment by nilswellhausen** [comment]
Screen Shot 2020-11-05 at 11 29 14 AM

**Comment by nilswellhausen** [comment]
I can also change colors etc. if there is a preference.

**Comment by vincerubinetti** [comment]
That second one looks cooler imo. Colors are good.

**Comment by rando2** [comment]
Just pushed the blue one with the cool spikes as thumbnail.png!

**Comment by vincerubinetti** [comment]
Also here are the [manubot thumbnail guidelines](https://github.com/manubot/catalog#thumbnail-guidelines). Take a quick look.

@rando2 did you see my edit to the previous comment? That particular screen grab of the second image with spikes is off-center. Make sure to fix that before merging. Also check that the image is square.

**Comment by rando2** [comment]
Oooh I looked and didn't notice, it's very subtle! I'm not sure how to crop pictures on this computer but I'll try to figure it out.

**Comment by rando2** [comment]
OK hopefully that worked, I'm definitely not on everyone else's visualization level! 
<https://github.com/rando2/covid19-review/blob/thumbnail/content/images/thumbnail.png>

**Comment by vincerubinetti** [comment]
@rando2 that looks good, thanks!

**Review by dhimmel — APPROVED** [review]
Beautiful

**Review by agitter — APPROVED** [review]

**Pull request merged**
