### PR TITLE
Update status of vaccine manuscripts

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

I'm going to submit them today (I was waiting for the second one to go up on arXiv, but it seems like that might take a while). I'll tag someone for review once that is finished!

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Review by agitter — COMMENTED** [review]
Can we please stick the Zenodo release archive badge at the top of the readme or near this table? I was looking for it recently and it took a while to find the DOI.

[DOI](https://doi.org/10.5281/zenodo.5532921)

**Comment by agitter** [comment]
@rando2 I pushed some commits directly to help with project maintenance after the latest submissions.  As part of that, I made new releases for the traditional and novel vaccines manuscripts.  I'm now making separate releases for both the source files on the master branch and the rendered documents on the output branch.  I think we should archive both.

I started updating the readme table too, but please take a final review yourself.

**Comment by rando2** [comment]
Thank you for doing this @agitter! It looks great.

**Review by agitter — APPROVED** [review]
I'll approve so you can merge if this looks good.  We can make another small update once #1175 is resolved.

**Pull request merged**
