### PR TITLE
Add @ShiktaDas to author list

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

This PR is for @shiktadas to add her info to the author list!

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by shiktadas** [comment]
Is there a template I need to fill?

**Comment by rando2** [comment]
@shiktadas if you go to the "files" tab, you can see the info we need from you! I wrote comments like [need this info] where I didn't want to guess.
<https://github.com/greenelab/covid19-review/pull/594/files>

**Comment by rando2** [comment]
@shiktadas just to make it a little easier, the info I wasn't sure about was:
    - orcid (if you have one)
   -  email: shikta_das@yahoo.co.uk
    - affiliation(s)
  
And then we just need you to confirm 
1. That you will follow the [code of conduct](CODE_OF_CONDUCT.md)
2. Whether you have any conflicts of interest we need to list ("no" is a perfectly valid answer!)

Thank you!

**Comment by shiktadas** [comment]
Orchid ID: https://orcid.org/0000-0002-8291-2788
Yes I will follow code of conduct 
No conflict of interest.

**Comment by rando2** [comment]
Thank you @shiktadas! Just to check, for affiliations, would it be:
1. C4X Discovery, London, United Kingdom
2. Medical Research Council LHA, Institute of Cardiovascular Studies, University College London, London, United Kingdom

Cheers!

**Comment by shiktadas** [comment]
Yes please it is correct.

**Comment by rando2** [comment]
Awesome @shiktadas! Hopefully we'll get you merged in today :)

**Pull request merged**
