### PR TITLE
Readme Enhancements

### PR DESCRIPTION
**Pull request by mprobson**
- Add buttons to Open and Issue and Fork
- Fix broken Internal links
- Add internal links to sections
- Small whitespace edits

### CODE REVIEW

**Comment by rando2** [comment]
Thanks for these fixes, @mprobson -- my only suggestion is to [add yourself at the bottom for software contributions](https://github.com/greenelab/covid19-review/blob/master/content/metadata.yaml). There is a formal process for determining authorship and this way we can track who contributed even if you end up meeting acknowledgements rather than authorship criteria.

**Comment by mprobson** [comment]
You're welcome! To confirm, that should be submitted as a separate PR, correct? I'm 99% sure that's the case according to the instructions but figured I'd leave a trail here for future external contributors.

**Comment by rando2** [comment]
Yes, please! [For now it seems it needs to trigger the manual action of me explicitly granting you read permissions.](https://github.com/greenelab/covid19-review/issues/15)

**Comment by mprobson** [comment]
Added, please see #16

**Pull request merged**
