### PR TITLE
Split and update appendix for vaccines

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

This builds on #1168, but I probably should have tried to merge it in a couple days ago because it's been tricky to keep up with the changes there. We'll see how good of a job I did once that merges!

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by agitter** [comment]
Let's finish #1168 and merge it back here before reviewing. If we can't finish that today, I'll need someone else to help review.  I generally trust any edits you decide to make.

I did move a few sections of the appendix already in #1168 and deleted a duplicated section, which may make the merge complicated here depending on where you started editing.

**Comment by rando2** [comment]
> Let's finish #1168 and merge it back here before reviewing. If we can't finish that today, I'll need someone else to help review. I generally trust any edits you decide to make.
> 
> I did move a few sections of the appendix already in #1168 and deleted a duplicated section, which may make the merge complicated here depending on where you started editing.

I've been manually updating my branch to follow your commits on #1168, so I'm hoping for a non-awful diff as long as we merge an intermediate PR to initiate the split... fingers crossed!

**Comment by rando2** [comment]
(By the way, the filename 24a is a stand-in. I need to rename these 4 files to be sequential but there are too many open PRs right now!)

**Comment by rando2** [comment]
Changes added to #1167 to simplify the number of PRs. Closing this PR without merging.

**Pull request closed without merging**
