### PR TITLE
Initial inclusion of COVID-19 TrialsTracker data

### PR DESCRIPTION
**Pull request by agitter**
### Description of the proposed additions or changes

This pull request add scripts to download, process, and summarize the COVID-19 TrialsTracker data.

### Related issues

#406

### Suggested reviewers (optional)

@rdvelazquez 

I'll continue working on a simple figure and additional statistics for this initial pull request.  We can discuss what to extract and plot in #406.

The dataset not updated on a daily basis, so I'm tracking two dates.  One is the most recent date of the git commit that updated the data file.  The other is the most recent date of when the trial data was updated, which is the relevant one to report in the manuscript.

### CODE REVIEW

**Comment by rdvelazquez** [comment]
This looks really cool @agitter! I pulled your branch down and was able to run it on my machine. I took a quick look at the code and things seem to make sense.

**Comment by agitter** [comment]
I added an initial draft of a figure for the clinical trials data.  I could probably remove some of the uninformative values, like study types with a count of 0 and trials with a "Not Applicable" phase. Any other suggestions for the first version of the figure?

**Comment by rdvelazquez** [comment]
The figures look nice!

**Comment by rando2** [comment]
Very cool @agitter! Is this OK to merge?

**Comment by agitter** [comment]
@rando2 this is ready to merge now if my final updates to the figures look good to you.  I eliminated some of the uninformative categories in the bar graphs.

**Comment by rando2** [comment]
> @rando2 this is ready to merge now if my final updates to the figures look good to you. I eliminated some of the uninformative categories in the bar graphs.

It looks great to me! I also looked through your code and learned how cool the manubot python library is!

**Comment by SiminaB** [comment]
Looks good! I wonder about "Traditional Medicine," which is in first place. Is that the same "Traditional Chinese Medicine" (TCM), which includes interventions like acupuncture etc? I know that sometimes those trials are controversial if they don't have a true placebo/comparator arm.
Are there only 3 recruitment statuses in the data? (Recruiting, Not recruiting, authorised?)

**Comment by agitter** [comment]
I didn't find a definition of "Traditional Medicine" yet, but I believe you are right that it refers to Traditional Chinese Medicine.  I agree those trials can be controversial.  Do you have suggestions on how to handle this?  Should I remove that category from the figure?  Or should I leave it, because that is the true breakdown of the trials data, but we comment on it in the manuscript text?

Yes, those were the only recruitment statuses.  There were another 4 studies with status "No Status Given", which I removed.

**Comment by SiminaB** [comment]
I think we should leave them in, just explain in the text what they refer to and maybe also check if most of them are undertaken in China - otherwise it would seem odd that we don't really discuss TCM as a possible treatment but a plurality of trials involve TCM. I guess trial location might be another interesting thing to pull out, though it may get messy with multi-institution trials.

**Comment by NickCEBM** [comment]
Hey all! Checked this out when I saw the cross-referenced issues. Just to chime in here, Traditional Medicine isn't just TCM, but can also be Traditional Medicines in other contexts. For instance, Iran has a number of herbal (and things like curcumin/honey) interventions being tested as well.

One could probably reasonably disagree with where we've been drawing that distinction but just wanted to let you know It's not just TCM.

**Comment by SiminaB** [comment]
Interesting points @NickCEBM! That's partly why I was suggesting to @agitter to get the location for the trials. Will add that suggestion in https://github.com/greenelab/covid19-review/issues/406

**Pull request merged**
