### PR TITLE
Update ORCID formatting

### PR DESCRIPTION
**Pull request by agitter**
### Description of the proposed additions or changes

Formatting recently added metadata

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by rando2** [comment]
Thanks @agitter! I think I made this mistake once and then just kept replicating my own error 🤦‍♀️

**Review by rando2 — APPROVED** [review]

**Comment by agitter** [comment]
It's something that Manubot should report or fix automatically.  That could be a small feature to add in the next release.

**Comment by rando2** [comment]
> It's something that Manubot should report or fix automatically. That could be a small feature to add in the next release.

Is there a good place to record these? (e.g., issue in rootstock?) I have a couple ideas as well I think just require some regex but might help with smoothing over some details in a big project like this! (Otherwise I'll just add this to my local list!)

**Comment by agitter** [comment]
This particular feature idea can be an issue in https://github.com/manubot/manubot.  It would require updating that Python package to reformat or check validity of author metadata when it is read in.

Other broader ideas for the Manubot workflow can be issues in https://github.com/manubot/rootstock

We can transfer issues so it isn't a big deal to decide which repo is best.  It's very helpful to have bug reports and feature requests logged as issues so please feel free to add some.

**Pull request merged**
