### PR TITLE
Reorganize clinical trials fig to meet journal requirements

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

I had to split the figure up into each panel for the original submission (due to file size requirement of < 20 Mb). The feedback from the journal was: 

> Figure 2 was submitted in multiple panels. Figures must be assembled to form complete figures prior to submission (Figure 1 is okay due to sizing and fonts size.)

> Please review the guidelines for acceptable figure files below and resubmit the figures at your earliest convenience. Figures should be provided at 100% of their print dimensions so that no reduction or enlargement is necessary. Figures should be no more than 6.87 inches wide (approximately 17.46 cm or 41.25 picas wide) and 9.06 inches high (approximately 23.01 cm or 54.37 picas high), while meeting all other criteria listed below for the specific file type being submitted. We also ask that you remove any figure legend text (although note that figure keys should be included), figure identifiers ("Figure 1") and/or excess white space from around the figure prior to increasing your image resolution and resizing your figures. Final font/text size must not fall below 6 points.

I reorganized the figure in the hopes that this will improve readability given these constraints. Here's what it looks like now:

ebmdatalab-trials

I'll wait for feedback on this PR to resubmit!

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Review by RLordan — APPROVED** [review]
It looks better this way I think. Kudos @rando2

**Review by agitter — APPROVED** [review]
This looks so much better!

If the file size is still an issue, could you submit the .svg version?

I'm assuming that you plan to submit your local version of the figure to the journal and wait for the external resources branch to update overnight.  That's okay with me.

**Comment by rando2** [comment]
Excellent, thank you @RLordan and @agitter! I just submitted my local version of the figure-- good call on using SVG in the future, especially if we specify the dimensions in `fig.save()` (to require minimal fussing in Preview)! I'll merge this in now.

**Comment by agitter** [comment]
@rando2 the version generated in the last external resources workflow has some overlapping text in panel D: https://raw.githubusercontent.com/greenelab/covid19-review/aace217c22c1dd548e9739fb8a74b1d143c4aa05/ebmdatalab/ebmdatalab-trials.png

Any idea why it might be different when you generated the figure?  Did you use the same conda environment that the workflow uses?

**Comment by rando2** [comment]
@agitter I did run it in the environment based on `environment.yml` in the root directory of the external-resources branch. I just created a new environment based on that .yml file and I'm getting the same result that I submitted to the journal.
ebmdatalab-trials

My local environment file is identical to the one here. I'll do some googling and see if I can think of anything!
[environment.yml.txt](https://github.com/greenelab/covid19-review/files/7238880/environment.yml.txt)

**Comment by agitter** [comment]
I ran it locally as well, and I get the same figure you do:
ebmdatalab-trials

Because there aren't any obvious issues, I suspect there is an unpinned package version that changed and is causing problems.  I noticed numpy is different in the latest GitHub Actions build and my local version of the environment.

I'll open a small pull request to explore this further.  We can leave the figure as-is for now.

**Pull request merged**
