### PR TITLE
Split general content (intro, discussion) across sections

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

This is a general proposal of how to move around the material from the intro and discussion. It is not incorporated very fluidly into the new locations in this PR, but I think separating these processes out will make it a lot easier to track the history of who worked on what!

### Related issues

This is rebased on top of #734, so should not be merged until after that one is. Right now the changes proposed in #734 are also proposed here. I'm marking it as a draft to make sure there is no issue.

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by agitter** [comment]
> I think separating these processes out will make it a lot easier to track the history of who worked on what!

I definitely agree with this.  One round of pull requests can remap existing content into files.  Then a separate round of pull requests can rephrase and edit as needed.

**Comment by RLordan** [comment]
Looks great, easy to follow.

**Comment by rando2** [comment]
@RLordan if this looks ok to you, would you mind approving it? Excited to finish up the therapeutics section!!! 🎉

**Review by ajlee21 — APPROVED** [review]
LGTM, just to clarify, is the idea that you're adding individual introduction and discussion sections to each of the different sections (i.e. therapeutics, methods, pathogenesis)?

**Comment by rando2** [comment]
@ajlee21 The journal actually requested that we split it up into a bunch of shorter papers! So this will be a special issue instead of a single paper. What I'm working on now is spreading all the info out among the separate papers! #731 for more info if you want it!

**Comment by RLordan** [comment]
> @RLordan if this looks ok to you, would you mind approving it? Excited to finish up the therapeutics section!!! 🎉
Sorry @rando2 I was traveling. I will have the check list for nutraceuticals ready before tomorrow. Thank you!

**Comment by rando2** [comment]
Safe travels @RLordan! I know this is often a very busy time of year! Enjoy your UPenn holidays!

**Comment by RLordan** [comment]
Thanks a million @rando2! Delighted to see the journals interest

**Pull request merged**
