### PR TITLE
Fix Manubot citations in intro, pathogenesis, diagnostics

### PR DESCRIPTION
**Pull request by agitter**
### Description of the proposed additions or changes

This corrects broken references for the first sections of the review.  I made my best attempt to specify authors for websites.  Here are a few unresolved questions:
- #396 added `doi:10.1101/2020.05.14.09613`, and I can't figure out what bioRxiv preprint that sound be.  Any ideas @rando2 or @ajlee21?  It was added to line 108.
- Is Cellex the author of https://www.fda.gov/media/136625/download ?
- Who should be listed as the author of the NY Forward guide (https://www.governor.ny.gov/sites/governor.ny.gov/files/atoms/files/NYForwardReopeningGuide.pdf)?  I didn't include one.  Maybe it is okay to leave it empty.

### Related issues

#371

### Checklist

- [X] Text is formatted so that each sentence is on its own line.

- [X] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by rando2** [comment]
@agitter thank you so much for fixing these! 
- I had typo-ed that doi, it should hopefully be fixed now
- Having cited "Illumina" many times in various pieces of writing, I think Cellex is a good solution to attributing authorship for that pdf!
- None of my usual tricks worked for finding authorship for this PDF. There is a list of advisory board members on page 99, but it's not clear that they're the ones who wrote the document.

**Comment by agitter** [comment]
Thanks for the quick comments @rando2.  I'm still watching the builds and fixing my JSON typos.  I'll comment again when the build looks good..

**Comment by agitter** [comment]
All the new manual references look good in the AppVeyor preview except for https://rt.live/  Manubot is still using the automatic reference data instead of my manual override.  I'm attempting to force it to use the manual entry.

**Comment by agitter** [comment]
I finally figured out the rt.live problem.  If the URL ends in `/`, the manual reference doesn't work.

This could be reviewed and merged now.  Or if it stay open, I'll add manual references for the other sections later this week.

**Comment by rando2** [comment]
Oh interesting! I'll try to keep an eye out for those. In the interest of avoiding any merge conflicts, I merged now!

**Pull request merged**
