### PR TITLE
Update metadata.yaml

### PR DESCRIPTION
**Pull request by scapone01**
### Description of the proposed additions or changes
 Addition of author.

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by agitter** [comment]
I'm glad the pull request worked @scapone01.  I'll debug why the Manubot build failed.  The yaml file is very sensitive about whitespace.

**Comment by scapone01** [comment]
Thank you so much, I was concerned that I broke the ManuBot haha

**Comment by agitter** [comment]
It worked this time:
image

We may want to expand your contributions later based on your writing in #374, but I'll let @rando2 review contributions when we are closer to submission.

**Comment by scapone01** [comment]
> It worked this time:
> image
> 
> We may want to expand your contributions later based on your writing in #374, but I'll let @rando2 review contributions when we are closer to submission.

@agitter Thank you so much for your help.

**Pull request merged**
