### PR TITLE
Add tab-delimited list of Mount Sinai Immunology Trainees & Faculty

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

The full list of Mount Sinai Immunology Trainees & Faculty (who wrote the reviews in the appendix) is here: https://www.nature.com/articles/s41577-020-0319-0 
This just adds a tsv with those names, one per line

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by rando2** [comment]
Order should be preserved (trainees first, in the order used in the paper, then faculty, in the order used in the paper) but I can adjust if desired!

**Comment by agitter** [comment]
Could we also cite https://www.nature.com/articles/s41577-020-0319-0 in the Methods:

> Appendix A contains summaries written by the students, post-docs, and faculty of the Immunology Institute at the Mount Sinai School of Medicine [747; **@doi:10.1038/s41577-020-0319-0**]

**Comment by rando2** [comment]
@agitter that's perfect! Added it here.

**Review by cgreene — APPROVED** [review]
Looks good!

**Pull request merged**
