### PR TITLE
Update external-resources branch

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

It doesn't seem like there's been an update to the csse data, so the new figures haven't generated. I ran it locally and pushed the updated figures and json file to try to get the figures generated in the manuscripts into the correct format.

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by agitter** [comment]
The GitHub Actions build is [failing ](https://github.com/greenelab/covid19-review/runs/3257681492?check_suite_focus=true#step:4:1) at this step, and I can't run the code locally either.   Let's try to diagnose the root cause.

GitHub's error is
```
Traceback (most recent call last):
  File "csse/generate-csse-stats.py", line 194, in <module>
    main(args)
  File "csse/generate-csse-stats.py", line 63, in main
    missing_df = pd.DataFrame(index=missing_dates, columns=sars_daily.columns)
  File "/usr/share/miniconda3/envs/covid19/lib/python3.7/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/usr/share/miniconda3/envs/covid19/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 239, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "/usr/share/miniconda3/envs/covid19/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1440, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'
```

My local error is
```
Traceback (most recent call last):
  File "csse/generate-csse-stats.py", line 199, in <module>
    main(args)
  File "csse/generate-csse-stats.py", line 104, in main
    ax = daily_cases.plot(kind='line', linewidth=2, ax=axes_list[0])
  File "C:\Users\agitter\.conda\envs\covid19\lib\site-packages\pandas\plotting\_core.py", line 847, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
  File "C:\Users\agitter\.conda\envs\covid19\lib\site-packages\pandas\plotting\_matplotlib\__init__.py", line 61, in plot
    plot_obj.generate()
  File "C:\Users\agitter\.conda\envs\covid19\lib\site-packages\pandas\plotting\_matplotlib\core.py", line 263, in generate
    self._make_plot()
  File "C:\Users\agitter\.conda\envs\covid19\lib\site-packages\pandas\plotting\_matplotlib\core.py", line 1085, in _make_plot
    **kwds,
  File "C:\Users\agitter\.conda\envs\covid19\lib\site-packages\pandas\plotting\_matplotlib\core.py", line 1104, in _plot
    lines = MPLPlot._plot(ax, x, y_values, style=style, **kwds)
  File "C:\Users\agitter\.conda\envs\covid19\lib\site-packages\pandas\plotting\_matplotlib\converter.py", line 66, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\agitter\.conda\envs\covid19\lib\site-packages\pandas\plotting\_matplotlib\core.py", line 656, in _plot
    return ax.plot(*args, **kwds)
  File "C:\Users\agitter\.conda\envs\covid19\lib\site-packages\matplotlib\axes\_axes.py", line 1667, in plot
    self.add_line(line)
  File "C:\Users\agitter\.conda\envs\covid19\lib\site-packages\matplotlib\axes\_base.py", line 1902, in add_line
    self._update_line_limits(line)
  File "C:\Users\agitter\.conda\envs\covid19\lib\site-packages\matplotlib\axes\_base.py", line 1924, in _update_line_limits
    path = line.get_path()
  File "C:\Users\agitter\.conda\envs\covid19\lib\site-packages\matplotlib\lines.py", line 1027, in get_path
    self.recache()
  File "C:\Users\agitter\.conda\envs\covid19\lib\site-packages\matplotlib\lines.py", line 675, in recache
    y = _to_unmasked_float_array(yconv).ravel()
  File "C:\Users\agitter\.conda\envs\covid19\lib\site-packages\matplotlib\cbook\__init__.py", line 1388, in _to_unmasked_float_array
    return np.ma.asarray(x, float).filled(np.nan)
  File "C:\Users\agitter\.conda\envs\covid19\lib\site-packages\numpy\ma\core.py", line 7949, in asarray
    subok=False, order=order)
  File "C:\Users\agitter\.conda\envs\covid19\lib\site-packages\numpy\ma\core.py", line 2832, in __new__
    order=order, subok=True, ndmin=ndmin)
TypeError: float() argument must be a string or a number, not 'NAType'
```

This could be related to these `<NA>` values in `daily_totals` after the `pd.merge`
```
     Days  COVID-19 Deaths  COVID-19 Cases  SARS Cases  SARS Deaths
0      66               17             557        <NA>         <NA>
1      67               18             655        <NA>         <NA>
2      68               26             941        <NA>         <NA>
3      69               42            1433        <NA>         <NA>
4      70               56            2118        <NA>         <NA>
```

**Comment by rando2** [comment]
@agitter oh interesting! [It seems like it has to do with the numpy & pandas versions.](https://github.com/pandas-dev/pandas/issues/39520) I've been able to replicate the GitHub Actions error by running it in conda.

Would you be OK with me attempting to upgrade the version of pandas we use here? I am using 1.2.4 locally and had no issue!

**Review by agitter — APPROVED** [review]
Nice find.

> Would you be OK with me attempting to upgrade the version of pandas we use here?

Yes, that's my preferred solution.  Let's keep this environment up to date with the versions needed to run the latest code.  We can check the GitHub Actions logs tomorrow to make sure that the other Python scripts still work on the new environment.

It runs correct locally for me in the updated environment so I'll merge.

**Comment by rando2** [comment]
Thank you @agitter! 🤞

**Comment by agitter** [comment]
This update fixed the CI build as well: https://github.com/greenelab/covid19-review/runs/3285980568?check_suite_focus=true

**Pull request merged**
