### PR TITLE
Build docx for nutraceuticals

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

This updates the individual-manuscript.txt file to request a docx build of nutraceuticals, and updates the metadata for this paper per #749 

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by agitter** [comment]
The nutraceuticals manuscript will have to be added to `content/individual-manuscripts.txt` instead of `content/individual-manuscript.txt` to include it in the docx builds.

**Comment by rando2** [comment]
Thanks @agitter! I swear I used to have pretty good attention to detail 🤦‍♀️ 

@RLordan, there is now a docx version of the manuscript if you want to check it for any reason! You can download a folder with the main build and the nutraceuticals-manuscript.docx

**Review by agitter — APPROVED** [review]
The docx looks good to me.  It makes sense to only build the docx of the manuscript that is being prepared for submission.

I noticed that Casey's update in 22d83a5fefaa1f22baa6b2774e326ec6bf08f961 set the `coi` to `2020-01-20` instead of `2021-01-20`.  This could be a good time to fix that.

**Comment by RLordan** [comment]
> Thanks @agitter! I swear I used to have pretty good attention to detail 🤦‍♀️
> 
> @RLordan, there is now a docx version of the manuscript if you want to check it for any reason! For now, you can download a [folder](https://github.com/greenelab/covid19-review/suites/1920594298/artifacts/37805101) that contains the nutraceuticals-manuscript.docx. Once this merges in, you can go here: https://github.com/greenelab/covid19-review/tree/output

Super, just downloaded, will read as a word doc and see if I can find any small issues.

**Pull request merged**
