### PR TITLE
Update David Manheim date of COI and affiliations

### PR DESCRIPTION
**Pull request by davidmanheim**
### Checklist

- [x] Text is formatted so that each sentence is on its own line.

- [x] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Review by rando2 — APPROVED** [review]
Just to check @davidmanheim, does 1DaySooner have a city in Delaware? A quick google suggests no, but figured I would ask just in case (it will make the submission a bit easier!)

**Comment by davidmanheim** [comment]
Not as far as I am aware, no.

**Comment by davidmanheim** [comment]
(Closed by accident - whoops!)

**Comment by rando2** [comment]
Thanks @davidmanheim! It would be easy to explain this in the cover letter so I'm not super worried, even though I will have to be a bit renegade with the author form!

**Pull request merged**
