### PR TITLE
Make vaccines maps easier to read

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

These edits do the following:
1. Edit code to set color scale within each paper
2. Increase size of map and the dpi to see how it looks

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Review by agitter — APPROVED** [review]
I don't know `plydata` syntax, but the code updates look reasonable.  Could you please commit the updated figures so we can see the diff?  The new example figures you copied look good.

**Comment by agitter** [comment]
Thanks, these do look nice.  The updated scale is helpful for the novel vaccines figures.

Do you think we need to make the title (and scale bar?) text a larger font now that the figure size is bigger overall?  Once these are resized in the manuscript, the font sizes might look small.

**Comment by rando2** [comment]
@agitter good point! I also caught that "NaN" values are causing an issue in the json (that I don't think actually affects the manuscripts, but seems worth fixing) so I'll tag you when I have both of these sorted out!

**Review by RLordan — APPROVED** [review]
Super improvement, thanks @rando2

**Comment by rando2** [comment]
Thank you @RLordan and @agitter! What do you think of this?

**Comment by agitter** [comment]
That title size looks good to me

**Pull request merged**
