### PR TITLE
Added review for a recent preprint Ravindra et al.

### PR DESCRIPTION
**Pull request by bansalvi**
### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by rando2** [comment]
Per the discussion in #346, we will want to either put this in the Issues section, or add it as a file in [this folder](https://github.com/ismms-himc/covid-19_sinai_reviews/tree/master/markdown_files), depending on @cornhundred's preferences

**Comment by rando2** [comment]
@bansalvi do you have the text of your review readily available such that you could add it as a comment here? I can use it to open a PR but that would be easiest way to get started :)

**Comment by rando2** [comment]
@cgreene Turns out, this was already reviewed by the Mount Sinai team <https://github.com/ismms-himc/covid-19_sinai_reviews/blob/master/markdown_files/10.1101-2020.05.06.081695.md>!
@bansalvi has opened it as an issue in #348 and I linked the Mount Sinai review.
@cornhundred just to loop you in!

**Comment by bansalvi** [comment]
> @cgreene Turns out, this was already reviewed by the Mount Sinai team https://github.com/ismms-himc/covid-19_sinai_reviews/blob/master/markdown_files/10.1101-2020.05.06.081695.md!
> @bansalvi has opened it as an issue in #348 and I linked the Mount Sinai review.
> @cornhundred just to loop you in!

Ohhhh. I checked carefully yesterday and also day before. May be they did it very recently.

**Comment by rando2** [comment]
@bansalvi no worries, I know things are also changing rapidly over there!

**Comment by cornhundred** [comment]
Sorry, I had taken a few days off from updating reviews

**Pull request closed without merging**
