### PR TITLE
Addition of author

### PR DESCRIPTION
**Pull request by soumitagh**
Add author info (Soumita Ghosh)

github: soumitagh
    name: Soumita Ghosh
    initials: SG  
    orcid: 0000-0002-2783-2750
    email: soumita84@gmail.com
    contributions:
        - Writing - Original Draft
    affiliations:
    Institute of Translational Medicine and Therapeutics, Perelman School of Medicine,University of Pennsylvania,Philadelphia, Pennsylvania, United States of America    

      coi:
      string: "None"
      lastapproved: !!str 2020-04-28

### CODE REVIEW

**Comment by soumitagh** [comment]
@rando2 :Thank you.

**Comment by soumitagh** [comment]
@rando2 : My name does not appear in the author list in the first page of review. Is there a time lag/bug in the software? let me know needful.

**Comment by rando2** [comment]
> @rando2 : My name does not appear in the author list in the first page of review. Is there a time lag/bug in the software? let me know needful.

@soumitagh I'm seeing you there! <https://greenelab.github.io/covid19-review/> :)
Currently you are last author -- we will rearrange at the end according to the procedures outlined in the CONTRIBUTING.md file.

**Comment by soumitagh** [comment]
thanks.I see it now .:)

**Pull request merged**
