### PR TITLE
Updates to figures for Therapeutics manuscript

### LINKED ISSUE #736: Case/Death Tracking Figure (Currently Figure 1)
**Is your feature request related to a problem? Please describe.**
There had been some previous feedback that the figure showing the accumulation of deaths over time wasn't super closely tied to the content of the manuscript in that section.
I'm wondering if instead we'd want to try to modify it to show cases over time (from the same data source) alongside the SARS cases from 2002-03

**Describe the solution you'd like**
The same data source has case information for COVID-19, so it should not be a huge switch to use a different data source there. It's a little harder to find data for SARS (and I had also considered MERS, but couldn't find anything usable).
The best resource I've found is this one: https://www.kaggle.com/imdevskp/sars-outbreak-2003-complete-dataset?select=sars_2003_complete_dataset_clean.csv

It scrapes the WHO website to pull the updates case numbers for every day from March to July 2003 (WHO started releasing SARS reports in March, the pandemic was classified as under control in July). It would be better to have data going back further, but I haven't found where that would be.

For MERS, there are some graphs circulating online (e.g., [this one](https://lh3.googleusercontent.com/proxy/ryyoG1o_K2bhhboKfd9NOxEl0EyvUbmFEyXVzCTAVPFkUqqpSTtntO7YsHDvC0KWWaXG2khKG6Pasqw-XpmAkHlJuHFtrLXxxcvYExHqlTWtyvCKyAY-7eq87SFUROI) that seem to show time series data, but it's not clear where their data sources are.

**Describe alternatives you've considered**
We definitely do not need to make this switch! I will open a PR soon that provides some additional context but I wanted to create this while I had everything fresh in my mind.
The gist is that these three pandemics followed very different trajectories despite all being coronaviruses with fairly high death rates (COVID-19 has the lowest death rate).

**Additional context**
Another possible issue is scale -- the SARS pandemic just didn't get out of control like this one did.

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

I was wondering if I could ask for some initial feedback on this adjustment to the CSSE figure for the intro in Therapeutics
We had gotten feedback from internal reviews that it didn't really communicate that much information, and since I reframed the intro of the therapeutics standalone to be about the differences between COVID-19 and SARS/MERS, I was hoping this might help illustrate it.
Obviously we have a huge issue of scale...
I can definitely clean this up but wanted to make sure the concept worked before I jump into aesthetics!

csse-deaths

UPDATE 7/29: I am also adding in minor adjustments to the clinical trials figure based on previous feedback

### Related issues

provides some steps towards #736 

### Suggested reviewers (optional)

@ajlee21 @agitter @cgreene @cbrueffer @nilswellhausen @RLordan 

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by RLordan** [comment]
Fair criticism I suppose. I think this figure is far more informative for a direct comparison. Maybe also overlaying confirmed cases over the same time period would be informative, but it would further mess with the scale issue. I won't nit-pick aesthetics haha

**Comment by ajlee21** [comment]
I think this is a very helpful visual to complement the new text!
* I agree with @RLordan that having number of cases would be helpful since the number of deaths is relative to the number of cases. I don't have a preference for if this is a separate panel vs overlaid. Though might be easier if its separate i guess...
* In terms of scaling, one thought is that you could have the left scale be for COVID-19 and the right scale be for SARS. I tend to find plots with 2 scales a bit confusing but I'm not sure of another alternative in order to overlay them
* Would it be helpful to add annotations for when the vaccine became available?

**Comment by rando2** [comment]
Thank you so much for looking this over, @RLordan and @ajlee21! I spoke with Casey and we agree that this is likely to be feedback we get at review. @ajlee21, your point about vaccines made Casey point out that we could combine this with the vaccine data @RLordan and I were incorporating into the vaccine paper. 

Given... certain impending constraints on my availability, I think it might make sense to use a lackluster figure 1 and just try to get this out to collaborators ASAP. I will open a new issue to make the changes you suggested as soon as I can!

**Comment by rando2** [comment]
If anyone knows how to smooth the SARS data over the weekends when there was no WHO report, I would be eternally grateful! I spent a long time messing around with SciPy and finally decided to cut my losses.
csse-deaths

**Comment by RLordan** [comment]
Thanks @rando2

**Comment by rando2** [comment]
Thank you everyone for the feedback! Here is a new version of the figure based on your thoughts.
csse-deaths

@agitter I like how it looks a little better with seaborn, but I think that might be a bit out of style? I'm definitely happy to use a different aesthetic if there's one we'd prefer, and I can make sure to standardize within each manuscript, if this does look better to everyone.

**Comment by rando2** [comment]
Based on the reviewer feedback, I also made some changes to the clinical trials figure:
ebmdatalab-trials

**Review by cgreene — APPROVED** [review]
I debated making some comments about the magic numbers re: the SARS-1 and SARS-CoV-2 emergence dates but those seem unlikely to be changed 🚀

**Pull request merged**
