### PR TITLE
Add visualization of manuscript stats

### LINKED ISSUE #952: Plotting manuscript progression for methods manuscript
For the ACM-BCB submission we could plot the following manuscript statistics over time:
- Number of authors who added themselves to metadata
- Number of references
- Word count

All of these are available in the files `variables.json` and `references.json` in the output branch of the repo.  Some quick Python experimentation shows how to access these values and the corresponding date:
```python
import json
variables = json.load(open('variables.json'))
>>> variables['pandoc']['date-meta']
'2021-04-28'
>>> variables['manubot']['date']
'April 28, 2021'
>>> len(variables['manubot']['authors'])
49
>>> variables['manubot']['manuscript_stats']['word_count']
131943
references = json.load(open('references.json', encoding='utf-8'))
>>> len(references)
1428
```

I don't know the most efficient way to get these for every commit in the output branch.  However
```
git log --pretty=format:"%h" > output-commits.txt
```
dumps a list of all commits to a text file that we could iterate over.

Pseudocode for an algorithm could look like:
- dump all commits on the output branch
- foreach output branch commit
- checkout the commit in a subprocess
- load the json files as shown above and store the commit sha1, manuscript date, author count, word count, and reference count in a row in a dataframe
- plot the data from the dataframe

Doing this with a Python script would be messy due to the subprocess calls to issue git commands, but it's possible and I don't know the GitPython package well enough to do it that way.  For example
```
subprocess.run(["git", "checkout", "3839cc2e"])
```
will checkout a specific commit from the output branch.

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

I'm not sure how it will work to have figure/statistic generation on the output branch, but I'm not totally sure if we need to worry about that today. I can just add the figure to the manuscript as a static .png file and fill in the stats for today's goals!

### Related issues

Closes #952 

### Suggested reviewers (optional)

@agitter 

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by rando2** [comment]
Happy to take feedback on figure: 
manuscript_stats

**Comment by agitter** [comment]
I don't think we should add these files to the output branch.  Even if the scripts have to run on the output branch, could you please move them and merge them into master instead?

I'll wait to review because merging to a different branch will probably require a new pull request.

**Comment by rando2** [comment]
@agitter Definitely! Just marking as draft for now to remind myself to move it -- since I loaded the figure manually into images/, I don't think this will make a different for today's goal!

**Comment by dziakj1** [comment]
Hello @rando2  -- I just wanted to check that you were aware of https://covariants.org/ .  It is an open source project and might be a good source of data for visualizations in the evolution, or perhaps pathogenesis, papers.  Thank you!

**Comment by rando2** [comment]
> Hello @rando2 -- I just wanted to check that you were aware of https://covariants.org/ . It is an open source project and might be a good source of data for visualizations in the evolution, or perhaps pathogenesis, papers. Thank you!

Very cool @dziakj1! Thank you for letting me know!

**Comment by dziakj1** [comment]
> 
> 
> > Hello @rando2 -- I just wanted to check that you were aware of https://covariants.org/ . It is an open source project and might be a good source of data for visualizations in the evolution, or perhaps pathogenesis, papers. Thank you!
> 
> Very cool @dziakj1! Thank you for letting me know!

I'm holding out for the Delta Plus Plus Platinum Edition with a celebrity endorsement by Thanos.
(Just kidding - God forbid!)

**Pull request closed without merging**
