### PR TITLE
A new paper about vitamin D deficiency from last week

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

Hey Ronan, I saw this paper and thought it seemed interesting and might worth adding as a citation if you think it fits!

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Review by RLordan — APPROVED** [review]
Perfect @rando2 , thanks for updating I only just read it myself. There is now 17 observational studies looking at the association between vit D and COVID. only 2 were skeptical of the association. The evidence is building.

**Comment by rando2** [comment]
It's super interesting for sure! I kind of wonder if there could be some conditions associated with vitamin D deficiency and also with increased susceptibility to COVID-19, but it definitely seems worth it to control what we can control (aka vitamin D status!)

**Comment by RLordan** [comment]
> It's super interesting for sure! I kind of wonder if there could be some conditions associated with vitamin D deficiency and also with increased susceptibility to COVID-19, but it definitely seems worth it to control what we can control (aka vitamin D status!)

You are completely correct, risk factors like CVD, cancer, diabetes, hypertension, and age all associated with low vit D, but in the former conditions rcts not so confident that supplementation helped... particularly for CVD, very mixed results.

**Comment by rando2** [comment]
@RLordan that's super interesting!!! You are always welcome to press merge in these situations, I just check periodically to see if the builds worked (all green at the bottom) so I'll hit it now :)

**Pull request merged**
