### PR TITLE
Rough outline of evolution manuscript

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

This is a rough outline of the sections we will want to add to get a standalone evolution manuscript. Early on there were some discussions of zoonotic transfer, etc. in the issues that we might want to make sure we read while developing this!

### Suggested reviewers (optional)

@Sergey-Knyazev

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by RLordan** [comment]
Do you want to include a bit about the B.1.1.7 variant and other variant of concern here? I can start part of it this week.

**Review by Sergey-Knyazev — APPROVED** [review]

**Comment by RLordan** [comment]
Very cool figures of the B.1.1.7 variant (and others) detection that might be worthwhile incorporating

https://cov-lineages.org/global_report_B.1.1.7.html

**Comment by rando2** [comment]
@rlordan that would be fantastic! @sergey-knyazev and I had briefly discussed the UK and SA variants on #750 so I think we'd both be excited to give feedback!

**Comment by RLordan** [comment]
> @RLordan that would be fantastic! @Sergey-Knyazev and I had briefly discussed the UK and SA variants on #750 so I think we'd both be excited to give feedback!

Perfect, i will get on it!

**Pull request merged**
