### PR TITLE
Add Topic-First Tracking of New Papers

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes
The number of preprints is exploding, and we want to encourage communities forming around shared interests (e.g., #92 ) so that we can help move people from #17 onto specific components of the project.

The goal here is to help people find papers of interest and see if anyone else has already read that paper -- for example, a paper evaluating administration of Remdesivir + hydroxychloroquinine would be of interest to writers working on sections about both drugs.

In this PR, you'll find the code to automatically scan the [CDC's COVID-19 Research Article Database](https://www.cdc.gov/library/researchguides/2019novelcoronavirus/researcharticles.html) where they're already systematically identifying everything related to COVID-19 (thanks, @dziakj1 , this was a game-changing suggestion!) and select papers related to individual topics of interest.

### Demo Product
[Dummy Hub: Remdesivir](https://htmlpreview.github.io/?https://github.com/rando2/covid19-review/blob/AddTracker/litsearch/bytopic/Remdesivir.html)
[Dummy Hub: Tocilizumab](https://htmlpreview.github.io/?https://github.com/rando2/covid19-review/blob/AddTracker/litsearch/bytopic/Tocilizumab.html)

### Workflow
Run [`Run_Updates.R`](https://github.com/rando2/covid19-review/blob/AddTracker/litsearch/Run_Updates.R) to:
1. Look at the CDC website to find the most up-to-date list of COVID-19-related papers
2. Pull from [`keywords.txt`](https://github.com/rando2/covid19-review/blob/AddTracker/litsearch/keywords.txt) to filter for papers that use relevant words in the Title, Abstract, or Keywords
3. Write TSV file of relevant article for each therapy
4. Generate .Rmd files that display information in the TSV file corresponding to each therapy
5. Run the .Rmd file to use knitr to create a (user-friendly) HTML-based Topic Hub

### Additional Development Needed
1. We would need to determine the keywords we want to use. The ones I used are just an example.
2. I need to adjust the workflow so that we can update the TSV file through PRs to add issue numbers, etc. and then not lose that information when I check for updates. This would allow for collaborative updating of the tracking, but the HTML files won't automatically regenerate.
3. Originally I was picturing a Jupyter notebook so that anyone could run updates, but haven't quite figured out how to implement that without potentially introducing problems. 
4. It's not ideal that these are HTML files right now. There seem to be [ways to convert Rmd to md using pandoc](https://rmarkdown.rstudio.com/docs/reference/md_document.html) -- would this interfere with Manubot at all?
5. Are links to issues, people, and PRs the info that will help people self-organize? Is there other information that we want to include? If we were doing a systematic review, we would formally include/exclude, but we decided against doing that here. We could also potentially tag things as review paper, clinical trial, observational study, etc.?

### Suggested reviewers (optional)
I'm looking for methodological feedback, usability feedback, and technical suggestions. I'm tagging everyone I can think of who has contributed to related conversations:
@SiminaB @cgreene @agitter @rdvelazquez @dziakj1 @LucyMcGowan @ressy @juliettemarie0405 

### Note
As a SQL enthusiast, I want to note that I originally tried to use SQLite as the backend, but there is no reasonable primary key (all character sets are fair game in titles, most papers don't have a DOI, and some papers have non-unique titles, e.g., "Editorial") and it turned into a huge headache!

### CODE REVIEW

**Comment by dziakj1** [comment]
I suppose you could try to run a bag-of-words clustering on the paper titles and keywords from the CDC's file, and see if you get useful clusters out of them, but that seems like a long shot.
Incidentally, how many co-authors are you hoping to have on this article?  Are you looking to recruit dozens more?  If so, perhaps developing something very easy like a SurveyMonkey form for reviewing papers would allow biology and medicine experts to contribute without having to master Github.  But perhaps that would go too far away from your philosophy about how to develop the article.

**Comment by dziakj1** [comment]
Many of the currently 8000+ articles in the CDC's spreadsheet are just opinion papers or news reports, not clinical trials, and some only mention COVID-19 in passing.  It might help to filter or sort on the quality of the source, so that maybe a peer-reviewed article in a high-impact journal is guaranteed to be seen, and a paper on Bioarxiv or an obscure journal is not.  Of course, there is also a tradeoff here because the very newest preprints haven't had time to be peer-reviewed or published yet.

**Comment by rdvelazquez** [comment]
@rando2 This looks like a great idea! A few random thoughts:
- Were you thinking this would be run with continuous integration on each build?
- Depending on how much we wanted to automate, we could probably automatically add in related issues to the TSV file. Github has a nice api that we could query (https://developer.github.com/v3/issues/#list-repository-issues). It could also be helpful to show if the paper is cited in our paper which we could automatically get from here https://github.com/greenelab/covid19-review/blob/output/references.json. Both these things could be tricky to automate correctly (because of not all papers having DOIs and the title's needing to be fuzzy text matched) so it might be more trouble than it's worth but should be considered.
- I think the html looks good and might be preferable to markdown

I'd be willing to try to help with some of the automation if you wanted to go that route but... I don't know R (I know, I know 😞). But I could hack my way through some stuff or do pieces in python or js if needed.

**Comment by agitter** [comment]
I'll have to think more about the best organization, but it should be possible to run these R scripts in the GitHub actions workflow and deploy the output HTML to GitHub Pages.  We could add links from the readme (and manuscript?) to an overview HTML page that links to the individual hubs.  I don't currently see any reason why they would have to be converted to Markdown first to be processed by Manubot.

The number of items in these tables could present usability challenges.  If all keyword groups have 50-100 articles, it would take a fair amount of work to cross-reference issues and pull requests and open issues for missing articles.  The lack of standard identifiers in the CDC database makes it hard to automate any of that.

Would adding some heuristic filters help with the annotation?  For instance, retaining only articles with a unique title and a standard identifier (DOI, clinical trial, etc.) could eliminate many that we can't use anyway.

**Comment by rando2** [comment]
Thank you everyone so much for the feedback! I’m running a few analyses to look at the data in line with your comments and I hope to upload some additional information tomorrow!

**Comment by cornhundred** [comment]
Hi @rando2 and @dziakj1 we've done some unbiased clustering on this observable noteobook https://observablehq.com/@ismms-himc/covid-19-sars-cov-2-preprints-from-medrxiv-and-biorxiv

We see clustering by Biorxiv/Medrxiv and some sub-clusters

**Comment by rando2** [comment]
I was working on running this data through a bag-of-words example I found, but @cornhundred just shared [this](https://observablehq.com/@ismms-himc/covid-19-sars-cov-2-preprints-from-medrxiv-and-biorxiv) over on gitter, and it seems to address some of @dziakj1's questions!
To answer some of the other questions, about 66% of entries in the CDC dataset have DOIs. I visualized the distribution of articles per journal and it looks like medRxiv is by far the most frequent as of yesterday's update. Here are the 5 most frequent journals:
|Journal|Frequency|
|---|---|
| medRxiv  | 943  |
| SSRN  | 306|
| bioRxiv  | 277  |
| BMJ  | 218  |
| Nature | 174 |

**Comment by rando2** [comment]
Update: hopefully going to adapt @cornhundred's code over at https://github.com/ismms-himc/covid-19_sinai_reviews/tree/master/notebooks to meet our project's needs :)

**Comment by rando2** [comment]
This has gone in a different direction, so I'm closing.

**Pull request closed without merging**
