### PR TITLE
Clean up warnings

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

There are some warnings in the (now very fast!) manubot build. I'm trying to debug here but I think they're all caused by webpages that manubot couldn't read, so I added manually.

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by agitter** [comment]
```
Run bash build/build.sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'commit'
Error: Process completed with exit code 1.
```
We had this build failure on another recent pull request. That time I reran the failed job, and it completed successfully. It's somewhat concerning if it is recurring sporadically.

**Comment by rando2** [comment]
@agitter Interesting. I pulled the branch locally and it's running fine. Based on the fact that it's a key error, I would guess something is buggy with the way the branch is being read in by sys and not the build.sh script itself? I'll keep an eye on this and see if a pattern emerges.

**Review by agitter — APPROVED** [review]
The error also isn't affecting AppVeyor builds, so I'm planning to ignore it for now.

**Comment by agitter** [comment]
I checked the script and it must be coming from this line:
```
EXTERNAL_RESOURCES_COMMIT=$(curl -sS https://api.github.com/repos/greenelab/covid19-review/branches/external-resources | python -c "import sys, json; print(json.load(sys.stdin)['commit']['sha'])")
```
If something sporadically fails with that call to the GitHub API, we won't be able to parse the commit. It's okay to fail in that case because we need access to the commit from the external resources branch. This could have to do with GitHub stability or load. We could make the error message more descriptive.

**Pull request merged**
