### PR TITLE
Vaccine organizational overhaul

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

I'm trying to repitch this text to make it a little more dynamic for the reviewers (based on the feedback we got on therapeutics). The strategy is to contextualize & summarize here, then provide the super detailed analysis in an appendix. That's why I made two files for this manuscript for now and am copying text from the current text back over to the 22.vaccines.md in a new order. Some of it will stay in 23.vaccines-app.md (or another file) as appendices that provide greater detail about the particular vaccines.

This is very much a draft, but @ajlee21 and I were coordinating a bit, so I wanted to make sure it was out in the open.

If anyone has thoughts or wants to jump in to flesh out one of the "To Do" lines, I am more than happy to take feedback. But just keep in mind this is pretty preliminary right now! :)

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by ajlee21** [comment]
This outline looks great to me! I really like the new angle. Just a couple of fairly minor thoughts:

1. Do you think it would make sense to put the whole virus vaccines and subunit vaccines under the `historical vaccine development` section? And similarly for the other vaccine types under the `21st century approaches` section?
2. Do you think it would make sense to have a visualization like this to show the status of the different vaccines: https://covid19.trackvaccines.org/vaccines/ Or just link out to them in a sentence?

**Comment by rando2** [comment]
@ajlee21 I like both of those suggestions!!! For 2., @RLordan and I had been talking about making choropleths for each vaccine that can pull data from OWID and update automatically. I think that would fit with what you're describing?

**Comment by ajlee21** [comment]
For the visual I was thinking of something that displayed the status of the vaccine interms of which trial they were under, approved, distribution. Were you thinking of a visual of how distributed the vaccine is across the country? That would be a nice visual too

**Comment by rando2** [comment]
> For the visual I was thinking of something that displayed the status of the vaccine interms of which trial they were under, approved, distribution. Were you thinking of a visual of how distributed the vaccine is across the country? That would be a nice visual too

Ah, gotcha! I'm not sure if I can do that with the OWID data -- we can see which vaccines are being given out where, but not their exact approval status. However, I know they do have that on the nytimes website, so potentially the data are out there!

**Comment by rando2** [comment]
@RLordan @ajlee21 would you be OK with this being merged in? I think that might make it easier to integrate the open vaccine PRs with this!

**Comment by RLordan** [comment]
I’m good with it 😊

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: HM Rando ***@***.***>
Sent: Tuesday, April 6, 2021 5:34:39 PM
To: greenelab/covid19-review ***@***.***>
Cc: Lordan, Ronan <Ronan.Lordan@Pennmedicine.upenn.edu>; Mention ***@***.***>
Subject: [External] Re: [greenelab/covid19-review] Vaccine organizational overhaul (#923)


@RLordan<https://github.com/RLordan> @ajlee21<https://github.com/ajlee21> would you be OK with this being merged in? I think that might make it easier to integrate the open vaccine PRs with this!

**Comment by athril** [comment]
An interesting point in discussion could be antibody-dependent enhancement and vaccines.
Also, it is worth mentioning that Sanofi has launched its mRNA vaccine candidate clinical trial, after unsuccessful trials with efficiency of adjuvanted recombinant protein-based vaccine in elders:
https://www.sanofi.com/en/media-room/press-releases/2021/2021-03-12-07-00-00-2191846
Can write both parts if needed.
@rando2 @RLordan

**Pull request merged**
