### PR TITLE
Add markdown tables from JSON to vaccines ms

### PR DESCRIPTION
**Pull request by rando2**
### Description of the proposed additions or changes

Add tables listing approved vaccines from json file

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

### CODE REVIEW

**Comment by rando2** [comment]
Screen Shot 2022-03-31 at 5 50 52 PM

Yay, it worked! I'll add the rest in tomorrow and mark this for review once that's done

**Comment by agitter** [comment]
That's really cool that it worked!  Automating table generation has been a general Manubot question (https://github.com/manubot/rootstock/issues/461) that we didn't have an easy solution for.

**Comment by rando2** [comment]
Need #1116 to merge to add final table

**Comment by rando2** [comment]
The captions are just stand-ins for now, but I think I finally got everything formatted correctly!

**Review by ajlee21 — APPROVED** [review]
Nice! That is a really neat feature! Had a couple of minor notes:

1. Looks like Figure 6 is not rendered in the html, its just a thumbnail
2. The Table in 6.6 for Vaccine safety is really squished, but I'm not sure if there is a work around - maybe making it landscape if that is a possability?

**Comment by rando2** [comment]
Hi @ajlee21! Thank you so much for reviewing!

1.  Hmm super weird! I'll open an issue about that. That is a static figure, so surprising that it's giving us trouble. It does render in PDF:  
    
2.  6.6: I think I am going to cut or dramatically alter the vaccine safety table (the tables added here are just the lists of vaccines & manufacturers, sorry I didn't explain that better!)

**Comment by agitter** [comment]
This is really cool @rando2.  Too bad the methods manuscript is already published.  This would have been a great Manubot extension to highlight.

We can consider having the Python script sort these tables by vaccine name before writing the markdown.  That's low priority, however.

**Pull request merged**
