### PR TITLE
Minor fixes from #163

### PR DESCRIPTION
**Pull request by rando2**
Minor fixes for a whitespace issue and a header issue from #163

### CODE REVIEW

**Comment by rando2** [comment]
The raw diff looks crazy, but the rich diff looks pretty normal, I'm not sure what's happening.
I'm going to re-do from command line.

**Comment by cgreene** [comment]
I would not recommend editing this file. It is automatically generated and
will be overwritten.

**Comment by rando2** [comment]
> I would not recommend editing this file. It is automatically generated and will be overwritten.

@cgreene I am happy to drop these small formatting issues! They really don't seem important! It's awesome that these two projects are connected now!

**Comment by cgreene** [comment]
I am happy to make the changes upstream. Perhaps we should make a short
comment somewhere in the readme about how to make changes to this file?

**Comment by agitter** [comment]
@cgreene that will be part of my instructions to maintainers in #175

**Comment by rando2** [comment]
@agitter That would be great, apologies for misunderstanding this morning!

**Pull request closed without merging**
